apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: movie
        image: saurabh8770/movie-app
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
