apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: movie
        image: saurabh8770/movie-app
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "512Mi"
            cpu: "1024m"
          limits:
            memory: "1024Mi"
            cpu: "2048m"
